### ISSUE TITLE
Hiding a program in archive

### ISSUE THREAD

**Issue by milanovitch44** [mateoconlechuga/cesium#162]
If you want to hide a archived program, you have to unarchive, hide and archive the program. Can cesium do this automatically?

**Comment by mateoconlechuga** [comment]
It could do it automatically, but generally hidden programs are to be avoided, so Cesium likes to make it difficult to do. This is because hidden programs may cause issues with the OS in certain situations, and potentially lead to duplicate programs. I'll keep this issue open in the event anyone wants to try implementing it, but I have no plans in the short term to do so. Thanks for the feedback!

**Comment by milanovitch44** [comment]
Can I make something that warns you when you have duplicates?
Should that be a pop-up or a just a warning symbol?

**Comment by mateoconlechuga** [comment]
Sure, whatever you think is best

**Comment by Bryankaveen** [comment]
> If you want to hide a archived program, you have to unarchive, hide and archive the program. Can cesium do this automatically?

If you want to "unhide" the program, you'll need to unarchive it ; but... the calculator resets (RAM CLEARED). Can't fix this, I guess.

**Comment by milanovitch44** [comment]
Isn't the RAM cleared an error because there isn't enough RAM?
The unarchive-hide-archive cycle works on my calculator.

**Comment by mateoconlechuga** [comment]
Closing as the popup seems to be sufficient in most cases
