### ISSUE TITLE
Issue with lowercase letters and [ON] key shortcuts.

### ISSUE THREAD

**Issue by RoccoLoxPrograms** [mateoconlechuga/cesium#180]
**This only happens when `Enable [ON] key shortcuts` is turned on.** 
When you hold down the either of the arrow keys when your in lowercase A-lock, the calculator displays and/or does random things. Screenshot is provided below to better explain... (This seems to vary depending on the calculator and OS.)
1. Held down the down arrow (went to `stats` menu).
2. Held down the up arrow (went to `stats` menu.
3. Held down the right arrow (spammed `1`).
4. Held down the left arrow (did nothing).

![CEmu-Screenshot](https://i.ibb.co/kcb2Jzv/CEmu-Lowercase.png)

**Comment by mateoconlechuga** [comment]
Makes me think you are using an old Cesium -- I can't seem to reproduce this, and I'm fairly sure I fixed this a while back.

**Comment by darkwater4213** [comment]
Actually, I can reproduce this: up and down works normally, but holding left or right spams the `XFact` token (what on earth is that, anyway?).

I'm using the most current version of Cesium (as of like three weeks ago, so this might have been fixed since then idk) and TextLib by Dr. D'nar to urn lowercase typing on and off. I'm just now realizing that I haven't tested this in the TI-OS editor, but I will later and edit this. I don't know what version my TI-84+CE is, but I know it's on the most recent TI-OS `5.3.*` or possibly `5.4.*` -- I'll have to check. (Haven't upgraded past that for obvious reasons).
