### ISSUE TITLE
Small recap

### ISSUE THREAD

**Issue by Bryankaveen** [mateoconlechuga/cesium#205]
Hey everyone, I need to share some info about Cesium :
 - poweron password should be more usefull : Indeed, if we press reset button/connect to another calculator, password is skipped.
 - what is [on]+[sto] used for ? it just makes the screen full white

**Comment by adriweb** [comment]
- First one is not something that can be solved, due to how the calculator works, especially in recent OSes ; remember that this isn't a real security feature, rather a fun one providing a bit of protection.
- Make sure to download the latest release from yesterday, it should fix some issues with the screen invert feature for some calculators.

**Comment by Bryankaveen** [comment]
ok, how about a dark mode **only on calculator screen/python mode**. ?
Actually, I'm using "inverted colors" but I have to on/off this option cause **everything** is inverted colors. 

For the security thing, it's ok :)

**Comment by adriweb** [comment]
Well, Cesium doesn't have control over the rest - simply put, it "just" tells the LCD the invert the colors, so yes, literally everything will be inverted, it's not at all specific to which app is being run.
