### ISSUE TITLE
File transfer doesn't work

### ISSUE THREAD

**Issue by Darkturtle999** [mateoconlechuga/cesium#220]
I go into USB flash drive and although it says press prgm to transfer the files, they don't transfer.  I have enough space and I am trying to transfer a converted TI-Boy rom for pokemon red. I would put the file here but github doesn't support the file type.

**Comment by mateoconlechuga** [comment]
Thanks! I'll look into this :)

**Comment by mateoconlechuga** [comment]
@Darkturtle999 Are you trying to transfer the bundle or the zip with all the actual files inside of it? Are you asking for Cesium to support the transfer of bundle files?

**Comment by mateoconlechuga** [comment]
I'm going to close this issue as Cesium doesn't have any plans to support bundles (they are actually zip files) and in order to transfer roms use the "Download all files in a .zip" option and extract them to a folder on the USB drive:
 
![image](https://user-images.githubusercontent.com/9890252/190059727-66e1ff08-2d90-44c8-9663-0c41e72d200b.png)
