### ISSUE TITLE
Running Cesium resets the wait state value to 4

### ISSUE THREAD

**Issue by Melonchanism** [mateoconlechuga/cesium#279]
If the wait state value was changed by something like ADVSPEED, the wait state value will be reverted to 4 upon entering cesium, even if the value was meant to make the calculator faster.

**Comment by mateoconlechuga** [comment]
Cesium doesn't do this

**Comment by Melonchanism** [comment]
https://github.com/user-attachments/assets/4abdd32f-1f77-4909-9b8a-e4a08813da32

Testing on both an emulator shown here and an actual calculator, with and without usb restrictions, my conclusion hasn't changed, and this has happened every single time.

**Comment by adriweb** [comment]
IIRC, it's each program (that were built within the last few years) that actually does this when it exits due to the crt. Basically at the start it reduces the wait states a little bit (a safe value was found experimentally), then it restores them at the end. See around here: https://github.com/CE-Programming/toolchain/blob/d1f6d81effb6f202f529e0bd6013418e3614289e/src/crt/crt0.src#L508

So Cesium wouldn't be the one restoring the value to "normal".

Also note that on any hardware M or later (this includes any Python CE), changing the flash wait states doesn't do anything, it's already at the minimum (the hw architecture changed and there's a cache in front of the flash, making things run up to 3x faster already).

**Comment by mateoconlechuga** [comment]
Yes this is a program thing, Cesium does not touch the wait states
