### ISSUE TITLE
3.0.3 Wait command 

### ISSUE THREAD

**Issue by TheLastMillennial** [mateoconlechuga/cesium#71]
Cesium stops BASIC program when encountering a wait command, it looks like it encountered a pause, but wont proceed no matter how long you wait or which button you press. Requires you to [on] break out of the program.

**Comment by LAX18** [comment]
This is not a cesium bug, rather an OS bug. I had this issue LONG before Cesium 3.0.3 was released (Nov. 20th, 2017 iirc)

**Comment by onlymx13** [comment]
Why can't it be fixed?

On Aug 24, 2018 11:59 AM, "LAX18" <notifications@github.com> wrote:

This is not a cesium bug, rather an OS bug. I had this issue LONG before
Cesium 3.0.3 was released (Nov. 20th, 2017 iirc)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mateoconlechuga/cesium/issues/71#issuecomment-415866756>,
or mute the thread

**Comment by LAX18** [comment]
lol I can see you responded via email

I dunno, I think it has something to do with the RTC being funky. I have always had this issue with Wait from 2 days after I got my CE.

**Comment by jcgter777** [comment]
So 1 day after you got it, you didn't have any issues? 0_0

I have this feeling that it's a cesium boogie.

**Comment by LAX18** [comment]
@jcgter777 It worked until I first tried to use it (or at least I assume it worked). After that, it failed to work.
